Repository apt-sim/AdePT, pull requests merged in 2020-10, with the labels that each got.

#9 Added atomic ops type and BlockData concurrent container
  CMakeLists.txt
  base/inc/AdePT/Atomic.h
  base/inc/AdePT/BlockData.h
  base/inc/AdePT/Utils.h
  base/inc/AdePT/mpmc_bounded_queue.h
  test/CMakeLists.txt
  test/test_atomic.cu
  test/test_queue.cu
  test/test_track_block.cu
Labels: core

#16 Fix for counting used elements in BlockData.
  base/inc/AdePT/BlockData.h
Labels: bug, core

#21 Fix BlockData allocation and copying on host.
  base/inc/AdePT/Atomic.h
  base/inc/AdePT/BlockData.h
  base/inc/AdePT/mpmc_bounded_queue.h
  base/inc/CopCore/include/CopCore/CopCore.h
  base/inc/CopCore/include/CopCore/VariableSizeObj.h
  test/CMakeLists.txt
  test/test_track_block.cu
Labels: copcore, core

#29 Remove format CI action and document git clang-format
  .github/workflows/clang-format.yml
  CONTRIBUTING.md
Labels: infrastructure
