Repository apt-sim/AdePT, pull requests merged in 2020-09, with the labels that each got.

#7 Add draft contribution and CoC guides
  .flake8
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSES/CC-BY-ND-4.0.txt
Labels: documentation, work in progress

#6 Add copyright and checks
  .github/workflows/reuse.yml
  .gitignore
  AUTHORS.md
  CMakeLists.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC-BY-4.0.txt
  LICENSES/GPL-3.0-or-later.txt
  README.md
  cmake/CMakeSettings.cmake
  test/CMakeLists.txt
  test/cufisher_price.cu
  test/example_add.cu
  test/fisher_price.cpp
Labels: documentation

#8 Added cmake dependencies.
  CMakeLists.txt
  README.md
  cmake/RecordCmdLine.cmake
Labels: build
