Repository apt-sim/AdePT, pull requests merged in 2025-06, with the labels that each got.

#396 fix synchronization issue between SwapDeviceBuffers and TransferHitsToHost
  include/AdePT/core/AsyncAdePTTransport.cuh
  include/AdePT/core/PerEventScoringImpl.cuh
Labels: bug

#397 fix CI, disable reproducibility_regions test for async AdePT
  Jenkinsfile
  jenkins/adept-ctest.cmake
  test/regression/CMakeLists.txt
  test/regression/scripts/reproducibility.sh
Labels: bug, CI

#398 Field cleanup
  include/AdePT/kernels/electrons.cuh
  include/AdePT/magneticfield/fieldPropagatorRungeKutta.h
  src/AdePTTrackingManager.cc
Labels: bug, enhancement

#400 clean kernel and fix vecgeom version check
  CMakeLists.txt
  include/AdePT/core/AsyncAdePTTransport.hh
  include/AdePT/kernels/electrons.cuh
  include/AdePT/kernels/electrons_split.cuh
  include/AdePT/kernels/gammas.cuh
  include/AdePT/kernels/gammas_split.cuh
  include/AdePT/magneticfield/fieldPropagatorConstBz.h
Labels: cleaning
